#server.port: 9000
spring:
  main.allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    stream:
      default: 
         producer: 
          useNativeEncoding: true
         consumer:  
          useNativeEncoding: true  
      bindings:
        input:
          destination: useravro
          content-type: application/*+avro
          group: group-1
          concurrency: 3
        output:
          destination: useravro
          content-type: application/*+avro
      kafka:
         binder:        
           producer-properties:
             key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
             value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
             schema.registry.url: http://localhost:29096
           consumer-properties:
             key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
             value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
             schema.registry.url: http://localhost:29096
             specific.avro.reader: true